all:
	git clone https://github.com/BTCGPU/bitcore
	cd bitcore && git checkout 7d48f3bdfd9e6d99057f937fa9667899ba5d642d
	cd bitcore && rm -rf .git # Delete .git folder to reduce space
	cd bitcore && yarn
	rm -rf bitcore/node_modules/bitcore-node/bin/*.gz
	rm -rf bitcore/node_modules/bitcore-node/bin/bitcoin-*/bin/bitcoin-qt
	rm -rf bitcore/node_modules/bitcore-node/bin/bitcoin-*/bin/test_bitcoin
	rm -rf bitcore/node_modules/bitcore-node/test/*

clean:
	rm -fr bitcore
