#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/bitcore-btg/home \
			--quiet --gecos "bitcore-btg" bitcore-btg
		chown -R bitcore-btg /opt/bitcore-btg/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
